##### input data

In [9]:
import numpy as np

In [10]:
movie_categlog_score=np.genfromtxt('movie_catelog_score.csv',delimiter=',')

In [11]:
user_score=np.genfromtxt('user_score.csv',delimiter=',')

In [12]:
movie_categlog_score

array([[ 0.8,  0.1,  0. ,  0.2,  0. ],
       [ 0. ,  0.9,  0.8,  0. ,  0.3],
       [ 0.2,  0. ,  0. ,  0.8,  0. ],
       [ 0. ,  0. ,  0.1,  0. ,  0.7]])

In [14]:
user_score

array([[ 2.,  5.,  4.,  3.,  2.],
       [ 1.,  4.,  3.,  3.,  5.],
       [ 5.,  4.,  4.,  2.,  1.],
       [ 4.,  5.,  5.,  3.,  3.]])

#####  Score Prediction using Linear Regression

In [15]:
from sklearn import linear_model

In [16]:
regr = linear_model.LinearRegression()

In [17]:
for i in range(0,4):
    regr.fit(np.transpose(movie_categlog_score), user_score[i,:])
    y_pred = regr.predict([[0,0.5,0,0.4]])
    print(y_pred)

[ 2.55555556]
[ 3.25396825]
[ 2.80952381]
[ 4.11111111]


#####  User Based Collaborative filtering

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
cosine_similarity(user_score)

array([[ 1.        ,  0.89843414,  0.90050042,  0.97421603],
       [ 0.89843414,  1.        ,  0.72140842,  0.88741197],
       [ 0.90050042,  0.72140842,  1.        ,  0.95612264],
       [ 0.97421603,  0.88741197,  0.95612264,  1.        ]])

##### Trend 

In [20]:
import matplotlib.pyplot as plt

In [21]:
import pandas as pd

In [22]:
trend_data=pd.read_csv('trend.csv')

In [ ]:
plt.plot(pd.to_datetime(trend_data['date'],format='%Y-%m'),trend_data['Titanic'],label='Titanic')
plt.plot(pd.to_datetime(trend_data['date'],format='%Y-%m'),trend_data['Iron Man'],label='Iron Man')
plt.plot(pd.to_datetime(trend_data['date'],format='%Y-%m'),trend_data['Oceans 8'],label='Oceans 8')
plt.legend()
plt.xlabel('month')
plt.ylabel('views')

##### cold start problem
not enough historical interactions
##### exploit－explore tradeoff
exploit: what customer expect
explore: what customer maybe is interested in

##### Bandit algorithms

In [160]:
import math

In [167]:
interestes={'Comedy':0.8,'Action':0.2}
comedy_try=0
action_try=0
comedy_viewed=0
action_viewed=0
recommend_comedy_rate=[]
for i in range(0,10000):
    if i==1000:
        interestes={'Comedy':0.2,'Action':0.8}#customer changes his/her tast
    recommend_comedy_rate.append(comedy_try/(i+1))
    rd_number=rd.random()
    if i==0:
        interest=interestes['Comedy']
        comedy_try+=1
        if rd_number <=interest:
            comedy_viewed+=1
    elif i==1:
        interest=interestes['Action']
        action_try+=1
        if rd_number <=interest:
            action_viewed+=1
    else:
        score_comedy=comedy_viewed/(comedy_try+1)+math.sqrt(2*math.log(i+1)/comedy_try)
        score_action=action_viewed/(action_try+1)+math.sqrt(2*math.log(i+1)/action_try)
        if score_comedy>=score_action:
            interest=interestes['Comedy']
            comedy_try+=1
            if rd_number <=interest:
                comedy_viewed+=1
        else:
            interest=interestes['Action']
            action_try+=1
            if rd_number <=interest:
                action_viewed+=1

In [ ]:
plt.plot(recommend_comedy_rate,'.')

##### recommendation for articles
TF-IDF algorithm  
term frequency–inverse document frequency

In [24]:
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
german_stop_words=[line.strip() for line in open('/Users/401384/work_repo/analytics/reference_files/german_stop_words.txt').readlines()]

In [26]:
vectorizer = TfidfVectorizer(analyzer='word',stop_words=german_stop_words,lowercase=True)

In [27]:
article_list=[]
article_files=['article1.txt','article2.txt','article3.txt','article4.txt']
for article_file in article_files:
    article_list.append(
            open(article_file).read().replace('\r','').replace('\n','').replace('\t','')
    )
    

In [28]:
tfidf=vectorizer.fit_transform(article_list)

In [29]:
cosine_similarities = linear_kernel(tfidf, tfidf).flatten()

In [30]:
cosine_similarities

array([ 1.        ,  0.06840255,  0.11262395,  0.1957427 ,  0.06840255,
        1.        ,  0.27992742,  0.07617252,  0.11262395,  0.27992742,
        1.        ,  0.12541711,  0.1957427 ,  0.07617252,  0.12541711,  1.        ])